"""Add is_admin to client table

Revision ID: 077dcfcc4235
Revises: 
Create Date: 2024-10-31 09:24:36.750245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '077dcfcc4235'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'address', ['idAddress'], ['idAddress'])

    with op.batch_alter_table('loyal_client', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'client', ['idClient'], ['idClient'])

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'client', ['idClient'], ['idClient'])
        batch_op.create_foreign_key(None, 'delivery_types', ['id_deliveryType'], ['id_type'])

    with op.batch_alter_table('order_products', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'product', ['idProduct'], ['idProduct'])
        batch_op.create_foreign_key(None, 'order', ['idOrder'], ['idOrder'])

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('promo',
               existing_type=mysql.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('sold',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('shipped',
               existing_type=mysql.INTEGER(display_width=1),
               type_=sa.Boolean(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.create_foreign_key(None, 'category', ['idCategory'], ['idCategory'])

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'client', ['idClient'], ['idClient'])
        batch_op.create_foreign_key(None, 'product', ['idProduct'], ['idProduct'])

    with op.batch_alter_table('wish', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'client', ['idClient'], ['idClient'])
        batch_op.create_foreign_key(None, 'product', ['idProduct'], ['idProduct'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('shipped',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('sold',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('promo',
               existing_type=mysql.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('order_products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('loyal_client', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
